import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('TajMahal.png',0)
img_erode = cv2.imread('erosion.png',0)
img_dilated = cv2.imread('dilation.png',0)
img_opened = cv2.imread('open.png',0)
img_closed = cv2.imread('close.png',0)
kernel = np.ones((5,5),np.uint8)
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)
gradient_erode = cv2.morphologyEx(img_erode, cv2.MORPH_GRADIENT, kernel)
gradient_dilated = cv2.morphologyEx(img_dilated, cv2.MORPH_GRADIENT, kernel)
gradient_opened = cv2.morphologyEx(img_opened, cv2.MORPH_GRADIENT, kernel)
gradient_closed = cv2.morphologyEx(img_closed, cv2.MORPH_GRADIENT, kernel)
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)
tophat_erode = cv2.morphologyEx(img_erode, cv2.MORPH_TOPHAT, kernel)
tophat_dilated = cv2.morphologyEx(img_dilated, cv2.MORPH_TOPHAT, kernel)
tophat_opened = cv2.morphologyEx(img_opened, cv2.MORPH_TOPHAT, kernel)
tophat_closed = cv2.morphologyEx(img_closed, cv2.MORPH_TOPHAT, kernel)
plt.imshow(img)
plt.show()
plt.imshow(gradient)
plt.show()
plt.imshow(gradient_erode)
plt.show()
plt.imshow(gradient_dilated)
plt.show()
plt.imshow(gradient_opened)
plt.show()
plt.imshow(gradient_closed)
plt.show()
plt.imshow(tophat)
plt.show()
plt.imshow(tophat_erode)
plt.show()
plt.imshow(tophat_dilated)
plt.show()
plt.imshow(tophat_opened)
plt.show()
plt.imshow(tophat_closed)
plt.show()
