# Generated by Django 2.2.1 on 2019-11-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
