# Generated by Django 2.2.1 on 2020-02-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoTaskListing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenumber',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
