# Generated by Django 2.2.1 on 2020-02-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoTaskListing', '0002_auto_20200220_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlisting',
            name='effective_from',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='documentlisting',
            name='expires_on',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='documentlisting',
            name='latest_revision',
            field=models.DateField(default='2020-02-20'),
        ),
        migrations.AlterField(
            model_name='documentlisting',
            name='signing_date',
            field=models.DateField(default='2020-02-20'),
        ),
    ]
