# Generated by Django 2.2.1 on 2020-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(max_length=100)),
            ],
            options={
                'verbose_name': 'FileNumber',
            },
        ),
        migrations.CreateModel(
            name='DocumentListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_title', models.CharField(max_length=250)),
                ('latest_revision', models.DateField(default='2020-02-19')),
                ('name_of_companies', models.TextField(blank=True)),
                ('first_party', models.TextField(blank=True)),
                ('second_party', models.TextField(blank=True)),
                ('other_party', models.TextField(blank=True)),
                ('type_of_agreement', models.CharField(max_length=250)),
                ('signing_date', models.DateField(default='2020-02-19')),
                ('effective_from', models.DateField(default='2020-02-19')),
                ('tenure', models.CharField(max_length=250)),
                ('expires_on', models.DateField(default='2020-02-19')),
                ('renewal_provision', models.CharField(max_length=250)),
                ('notice_for_termination', models.CharField(max_length=250)),
                ('executed_by', models.TextField(blank=True)),
                ('name_of_product', models.TextField(blank=True)),
                ('custodian_type', models.CharField(max_length=250)),
                ('original', models.CharField(max_length=250)),
                ('duplicate', models.CharField(max_length=250)),
                ('concerned_person', models.TextField(blank=True)),
                ('contact_reference', models.TextField(blank=True)),
                ('remarks', models.CharField(max_length=250)),
                ('file_number', models.ForeignKey(default='general', on_delete='models.CASCADE', to='TodoTaskListing.FileNumber')),
            ],
            options={
                'ordering': ['-signing_date'],
            },
        ),
    ]
