# Generated by Django 2.2.1 on 2020-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoTaskListing', '0003_auto_20200221_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlisting',
            name='effective_from',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='documentlisting',
            name='expires_on',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='documentlisting',
            name='latest_revision',
            field=models.DateField(default='2020-02-21'),
        ),
        migrations.AlterField(
            model_name='documentlisting',
            name='signing_date',
            field=models.DateField(default='2020-02-21'),
        ),
    ]
