# Generated by Django 2.2.1 on 2019-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactListBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SL', models.IntegerField(max_length=120)),
                ('Name', models.TextField()),
                ('Number', models.IntegerField(max_length=120)),
            ],
        ),
    ]
