import cv2
img = cv2.imread('TajMahal.png',0)
cv2.imshow('Original', img)
cv2.waitKey()
cv2.imshow('Grayscale', img)
cv2.waitKey()
erode_img = cv2.imread('erosion.png', 0)
cv2.imshow('Grayscale_erode', erode_img)
cv2.waitKey()
dilated_img = cv2.imread('dilation.png', 0)
cv2.imshow('Grayscale_dilated', dilated_img)
cv2.waitKey()
opened_img = cv2.imread('open.png', 0)
cv2.imshow('Grayscale_opened', opened_img)
cv2.waitKey()
closed_img = cv2.imread('close.png', 0)
cv2.imshow('Grayscale_closed', closed_img)
cv2.waitKey()

