from textblob import TextBlob,Word
from textblob.wordnet import VERB,Synset
wiki = TextBlob("Python is a high-level, general-purpose programming language.")
print(wiki.tags)
print(wiki.noun_phrases)
testimonial = TextBlob("Textblob is amazingly simple to use. What great fun!")
print(testimonial.sentiment)
zen = TextBlob("Beautiful is better than ugly. "
               "Explicit is better than implicit. "
               "Simple is better than complex.")
print(zen.words)
print(zen.sentences)
for sentence in zen.sentences:
    print(sentence.sentiment)
sentence = TextBlob('Use 4 spaces per indentation level.')
print(sentence.words)
print(sentence.words[2].singularize())
print(sentence.words[-1].pluralize())
w = Word("octopi")
print(w.lemmatize())
w = Word("went")
print(w.lemmatize("v"))
word = Word("octopus")
print(word.synsets)
print(Word("hack").get_synsets(pos=VERB))
print(Word("octopus").definitions)
octopus = Synset('octopus.n.02')
shrimp = Synset('shrimp.n.03')
print(octopus.path_similarity(shrimp))
animals = TextBlob("cat dog octopus")
print(animals.words.pluralize())
b = TextBlob("I havv goood speling!")
print(b.correct())
w = Word('falibility')
print(w.spellcheck())
monty = TextBlob("We are no longer the Knights who say Ni. "
                 "We are now the Knights who say Ekki ekki ekki PTANG.")
print(monty.word_counts['ekki'])
print(monty.words.count('ekki', case_sensitive=True))
print(wiki.noun_phrases.count('python'))
b = TextBlob("And now for something completely different.")
print(b.parse())
print(zen[0:19])
print(zen.upper())
print(zen.find("Simple"))
apple_blob = TextBlob('apples')
banana_blob = TextBlob('bananas')
print(apple_blob < banana_blob)
blob = TextBlob("Now is better than never.")
print(blob.ngrams(n=3))
for s in zen.sentences:
    print(s)
    print("---- Starts at index {}, Ends at index {}".format(s.start, s.end))
en_blob = TextBlob(u'Simple is better than complex.')
print(en_blob.translate(to='es'))
chinese_blob = TextBlob(u"美丽优于丑陋")
print(chinese_blob.translate(from_lang="zh-CN", to='en'))
b = TextBlob(u"بسيط هو أفضل من مجمع")
print(b.detect_language())