# Generated by Django 2.2.1 on 2019-11-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
